run:
  concurrency: 4
  timeout: 3m

linters:
  disable-all: true
  enable-all: false
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - decorder
    - dogsled
    - dupl
    - dupword
    - gofumpt
    - goimports
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - grouper
    - ineffassign
    - interfacebloat
    - maintidx
    - misspell
    - nakedret
    - prealloc
    - reassign
    - revive
    - staticcheck
    - typecheck
    - unused

linters-settings:
  misspell:
    locale: US

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - linters:
        - gosec
      text: "^(G107|G204|G306):"
  exclude-files:
    - "internal/pkg/util/user/cgo_lookup_unix.go"

