git mv ./cmd/internal/cli/singularity.go ./cmd/internal/cli/apptainer.go
git mv ./cmd/internal/cli/singularity_test.go ./cmd/internal/cli/apptainer_test.go
git mv ./cmd/starter/engines/singularity_linux.go ./cmd/starter/engines/apptainer_linux.go
git mv ./dist/debian/singularity-container.dirs ./dist/debian/apptainer-container.dirs
git mv ./dist/debian/singularity-container.lintian-overrides ./dist/debian/apptainer-container.lintian-overrides
git mv ./dist/debian/singularity-container.examples ./dist/debian/apptainer-container.examples
git mv ./dist/rpm/singularity.spec.in ./dist/rpm/apptainer.spec.in
git mv ./internal/pkg/image/unpacker/squashfs_singularity.go ./internal/pkg/image/unpacker/squashfs_apptainer.go
git mv ./internal/pkg/image/unpacker/squashfs_no_singularity.go ./internal/pkg/image/unpacker/squashfs_no_apptainer.go
git mv ./docs/logos/singularity_v3.png ./docs/logos/apptainer_v3.png
git mv ./docs/logos/singularity_v3.svg ./docs/logos/apptainer_v3.svg
git mv ./examples/build-apptainer/build-singularity.def ./examples/build-apptainer/build-apptainer.def
git mv ./scripts/run-singularity ./scripts/run-apptainer
git mv ./e2e/internal/e2e/singularitycmd.go ./e2e/internal/e2e/apptainercmd.go
git mv ./pkg/util/loop/loop_singularity.go ./pkg/util/loop/loop_apptainer.go
git mv ./pkg/util/loop/loop_no_singularity.go ./pkg/util/loop/loop_no_apptainer.go
git mv ./pkg/plugin/callback/runtime/engine/apptainer/singularity.go ./pkg/plugin/callback/runtime/engine/apptainer/apptainer.go
git mv ./examples/debian/Singularity ./examples/debian/Apptainer
git mv ./examples/centos/Singularity ./examples/centos/Apptainer
git mv ./examples/sle/Singularity ./examples/sle/Apptainer
git mv ./examples/raspbian/Singularity ./examples/raspbian/Apptainer
git mv ./examples/library/Singularity ./examples/library/Apptainer
git mv ./examples/opensuse/Singularity ./examples/opensuse/Apptainer
git mv ./examples/shub/Singularity ./examples/shub/Apptainer
git mv ./examples/busybox/Singularity ./examples/busybox/Apptainer
git mv ./examples/scratch/Singularity.alpine ./examples/scratch/Apptainer.alpine
git mv ./examples/scratch/Singularity.busybox ./examples/scratch/Apptainer.busybox
git mv ./examples/self/Singularity ./examples/self/Apptainer
git mv ./examples/opensuse-arm64/Singularity ./examples/opensuse-arm64/Apptainer
git mv ./examples/arch/Singularity ./examples/arch/Apptainer
git mv ./examples/asciinema/Singularity ./examples/asciinema/Apptainer
git mv ./examples/instances/Singularity ./examples/instances/Apptainer
git mv ./examples/centos-arm64/Singularity ./examples/centos-arm64/Apptainer
git mv ./examples/apps/Singularity.cowsay ./examples/apps/Apptainer.cowsay
git mv ./examples/apps/Singularity ./examples/apps/Apptainer
git mv ./examples/ubuntu/Singularity ./examples/ubuntu/Apptainer
git mv ./examples/multistage/Singularity ./examples/multistage/Apptainer
git mv ./examples/scientific/Singularity ./examples/scientific/Apptainer
git mv ./e2e/testdata/Singularity ./e2e/testdata/Apptainer
