FROM ubuntu:24.04

ARG GOVERSION="go1.25.6"
ARG GOOS="linux"
ARG GOARCH="amd64"
ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin
ENV DEBIAN_FRONTEND=noninteractive

# Install system packages
RUN apt-get update && \
    apt-get install -y \
        build-essential \
	libsubid-dev \
	libseccomp-dev \
	uidmap \
	fakeroot \
	cryptsetup \
	tzdata \
	dh-apparmor \
	curl wget git && \
    apt-get install -y \
	autoconf automake libtool pkg-config libfuse3-dev \
	zlib1g-dev liblzo2-dev liblz4-dev liblzma-dev libzstd-dev

# Install GO
RUN wget -O /tmp/go${GOLANG_VERSION}.linux-${ARCH}.tar.gz https://go.dev/dl/${GOVERSION}.${GOOS}-${GOARCH}.tar.gz && tar -C /usr/local -xzf /tmp/go${GOLANG_VERSION}.linux-${ARCH}.tar.gz

# Install Apptainer
ADD . apptainer
RUN cd apptainer && \
    git clean -fdx && \
    ./mconfig && \
    make -C builddir && \
    make -C builddir install && \
    ./scripts/download-dependencies && \
    ./scripts/compile-dependencies && \
    ./scripts/install-dependencies

ENTRYPOINT ["/usr/local/bin/apptainer"]
CMD ["version"]
