#!/bin/bash -ex
# Copyright (c) 2021 Apptainer a Series of LF Projects LLC
#   For website terms of use, trademark policy, privacy policy and other
#   project policies see https://lfprojects.org/policies

# this script runs as root under docker

OS_TYPE="$1"
OS_VERSION="$2"

# build and install
yum install -y rpm-build make yum-utils gcc binutils util-linux-ng which
yum install -y libseccomp-devel e2fsprogs cryptsetup
yum install -y epel-release
yum install -y golang

# switch to an unprivileged user with sudo privileges
yum install -y sudo
# We need Git existing here prior to the run
yum install -y git
useradd -u 1000 --create-home -s /bin/bash testuser
echo "Defaults:testuser env_keep=DOCKER_HOST" >>/etc/sudoers
echo "testuser ALL=(ALL) NOPASSWD: ALL" >>/etc/sudoers
chown -R testuser .

su testuser -c '
  set -x
  set -e
  ./mconfig --only-rpm
  sudo yum-builddep -y apptainer.spec
  make -C builddir rpm
  sudo yum install -y $HOME/rpmbuild/RPMS/*/*.rpm
  BLD=`echo $HOME/rpmbuild/BUILD/apptainer-*`
  export GOPATH=$BLD/gopath
  PATH=$GOPATH/bin:$PATH

  apptainer exec library://alpine:3.11.5 /bin/true
'
