#!/bin/bash -ex
# Copyright (c) Contributors to the Apptainer project, established as
#   Apptainer a Series of LF Projects LLC.
#   For website terms of use, trademark policy, privacy policy and other
#   project policies see https://lfprojects.org/policies

# this script runs as root under docker --privileged

# install required package(s)
if [ "$OS_TYPE" = debian ] || [ "$OS_TYPE" = ubuntu ]; then
  apt-get update
  apt-get install -y curl rpm2cpio cpio e2fsprogs tzdata
elif [[ "$OS_TYPE" == *suse* ]]; then
  zypper install -y e2fsprogs curl cpio util-linux timezone
else
  # For Rocky Linux, CentOS, Fedora, etc.
  dnf install -y e2fsprogs cpio
  
  # Install runtime for rocky linux to build apptainer
  if [[ "$OS_TYPE" == *rockylinux* ]] && [[ "$OS_VERSION" -gt 9 ]]; then
    if ! dnf install -y shadow-utils-subid; then
      echo "Warning: Could not install shadow-utils-subid, apptainer may fail to run"
    fi
    if ! dnf install -y fuse3-libs fuse3-devel; then
      echo "Warning: Could not install fuse3 packages, container operations may fail"
    fi
  fi
fi

# switch to an unprivileged user
useradd -u 1000 --create-home -s /bin/bash testuser
rm -f /etc/subuid /etc/subgid

# Be careful not to use unescaped single quotes in these commands
su testuser -c '
  export PATH=$PATH:/usr/sbin
  set -x
  set -e
  rm -rf ins image*.sif overlay.img
  tools/install-unprivileged.sh -e -v apptainer-[1-9]*.$(arch).rpm '"$INS_OPTS"' ins
  
  # Handle library compatibility issues for Rocky Linux
  if [[ "$OS_TYPE" == *rockylinux* ]] && [[ "$OS_VERSION" -gt 9 ]]; then
    # Copy newer system libraries to override older extracted versions
    if [ -f /usr/lib64/libfuse3.so.3 ]; then
      cp /usr/lib64/libfuse3.so.3 ins/$(arch)/utils/lib/libfuse3.so.3
    fi
    if [ -f /usr/lib64/libselinux.so.1 ]; then
      cp /usr/lib64/libselinux.so.1 ins/$(arch)/utils/lib/libselinux.so.1
    fi
    if [ -f /usr/lib64/libsubid.so.4 ]; then
      cp /usr/lib64/libsubid.so.4 ins/$(arch)/utils/lib/libsubid.so.4
    fi
  fi
  
  (
  echo Bootstrap: docker
  echo From: '"$CONTAINER_VERS"'
  echo %post
  echo "  id"
  ) >image.def
  ins/bin/apptainer build image.sif image.def
  truncate -s 1G overlay.img
  mkfs.ext3 -F -O ^has_journal overlay.img
  ins/bin/apptainer exec --overlay overlay.img -f image.sif touch /bin/newfile
  ins/bin/apptainer exec -f image.sif ins/bin/apptainer exec --overlay overlay.img image.sif cat /bin/newfile
  ins/bin/apptainer exec --unsquash image.sif true
  echo testphrase|ins/bin/apptainer build --encrypt --passphrase image-e.sif image.sif
  echo testphrase|ins/bin/apptainer exec --passphrase image-e.sif true
'
