#!/bin/bash
# Copyright (c) Contributors to the Apptainer project, established as
#   Apptainer a Series of LF Projects LLC.
#   For website terms of use, trademark policy, privacy policy and other
#   project policies see https://lfprojects.org/policies

HERE=${0%/*}
PARENT=${HERE%/*}
if [ "$PARENT" = "$HERE" ]; then
    PARENT=.
fi
eval `grep ^hstgo_preferred_version= ${PARENT}/mconfig`
echo $hstgo_preferred_version
